### PR TITLE
Implementing dotnet core version awareness

### PR DESCRIPTION
**Pull request by Elycin**

### CODE REVIEW

**Comment by Wintereise** [comment]
How well tested is this? Code review not likely to be very helpful, try it out on some fresh VMs and share the results @Elycin

**Comment by Elycin** [comment]
I spun up a virtual machine in DigitalOcean's NYC3, as given in the screenshot in slack.
I'll run it on CentOS and Debian for good measure.

**Comment by Elycin** [comment]
Appears to be a byte-to-string bug I missed, fixing.

**Comment by Elycin** [comment]
Confirmed fixed, and manually tested.

```python
>>> install.get_sources_information()
>>> install.get_dotnet_core_path()
'/usr/bin/dotnet'
>>> install.is_dotnet_version_compatible("2.1.1")
False
>>> install.is_dotnet_version_compatible("2.1.2")
True
```

**Comment by Elycin** [comment]
Ubuntu 18.04 LTS System Installed dotnet core confirmed working.
image

**Comment by Wintereise** [comment]
@Elycin Great, does it behave well on the other distros as well? Do some cursory testing, likely is fine.

I'll merge after.

**Comment by Elycin** [comment]
Confirmed working on CentOS 7.5, anything else @Wintereise?
image

**Pull request merged**
